- hosts: all
  tasks:
    - name: Run the bash script install/let-encrypt 
      become: yes
      become_user: solenb
        - value: ukx721917NVUD
      shell: install-nc.sh
      shell: lets-encrypt-nc.sh 
  
  
 
