- hosts: all
  tasks:
    - name: Run the bash script install/let-encrypt 
      become: yes
      become_user: root
      shell: cd /home
      shell: git clone https://github.com/solenb/nextcloud-test.git
      shell: cd nextcloud-test
      shell: install-nc.sh
      shell: lets-encrypt-nc.sh 
  
  
 
