- hosts: all
  tasks:
    - name: Install the NextCloud server via Snapd
      become: yes
      become_user: root
      snap: 
        name: 
          - nextcloud
  tasks:
    - name: Configure the NextCloud server
      raw: nextcloud.manual-install solenb Temporary72
      raw: nextcloud.occ config:system:get trusted_domains
      raw: nextcloud.occ config:system:set trusted_domains 1 --value=nextcloud.solenb.fr
      raw: ufw allow 80,443
      raw: nextcloud.enable-https lets-encrypt <<< $'yes\nsolenbellouati@gmail.com\nnextcloud.solenb.fr' 
 
