- hosts: all
  tasks:
    - name: Install the NextCloud server via Snapd
      become: yes
      become_user: root
      snap: 
        name: 
          - nextcloud
  tasks:
    - name: Configure the NextCloud server
      raw: nextcloud.manual-install solenb Temporary72
      raw: nextcloud.occ config:system:get trusted_domains
      raw: nextcloud.occ config:system:set trusted_domains 1 --value=nextcloud.solenb.fr
  
  tasks:
    - name: Allow port for Firewall
      shell: ufw allow 80,443/tcp 
      args:
        warn: no
      
 
